apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-wi
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "3883c82b-b2fd-4e22-8aa7-e1e394e4c2d9"
    keyvaultName: "aks-kv-dev-vault-6e6303"
    tenantId: "6522877b-25bb-4989-9eb3-f323471a3bc3"
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
          objectVersion: ""